blank_issues_enabled: false
contact_links:
  - name: Math Kit
    url: https://github.com/sarahhudaib/Math-Kit
    about: Math Kit is an advanced GUI tool, that is made specifically for performing basic and advanced mathematical operations (as will be mentioned below) without any additional hassle as it insures that it serves the main purpose of providing a top-tier mathematical help with not much spent effort by the user.
    license: MIT License.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
    
